import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'exposure_state.dart';
import 'exposure_calculator.dart';

enum MeteringMode { spot, centerWeighted, matrix }

class AnalogViewfinderScreen extends StatefulWidget {
  const AnalogViewfinderScreen({super.key});

  @override
  State<AnalogViewfinderScreen> createState() => _AnalogViewfinderScreenState();
}

class _AnalogViewfinderScreenState extends State<AnalogViewfinderScreen> {
  MethodChannel? _methodChannel;
  EventChannel? _eventChannel;
  StreamSubscription? _eventSubscription;
  
  bool _isAELocked = false;
  double _lockedBaseEV = 8.0;

  List<int> _histogramR = List.filled(256, 0);
  List<int> _histogramG = List.filled(256, 0);
  List<int> _histogramB = List.filled(256, 0);
  int _maxHistogramValue = 1;

  Offset? _meterPoint;
  double _currentZoom = 1.0;
  bool _showHistogram = true;
  late ExposureState _exposureState;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        _exposureState.setUsingCameraSensor(true);
      }
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _exposureState = Provider.of<ExposureState>(context, listen: false);
  }

  @override
  void dispose() {
    _eventSubscription?.cancel();
    _exposureState.setUsingCameraSensor(false);
    Future.delayed(const Duration(milliseconds: 300), () {
      _exposureState.reinitializeSensor();
    });
    super.dispose();
  }

  void _onPlatformViewCreated(int id) {
    _methodChannel = MethodChannel('com.arWRKS.lelemeter/camera_methods_$id');
    _eventChannel = EventChannel('com.arWRKS.lelemeter/camera_events_$id');
    
    _eventSubscription = _eventChannel!.receiveBroadcastStream().listen((data) {
      if (!mounted) return;
      final map = Map<String, dynamic>.from(data);
      
      setState(() {
        _histogramR = List<int>.from(map['rHist']);
        _histogramG = List<int>.from(map['gHist']);
        _histogramB = List<int>.from(map['bHist']);
        _maxHistogramValue = map['maxVal'] as int;
      });

      double calculatedEV = map['calculatedEV'] as double;
      int hardwareIso = map['iso'] as int;
      int hardwareShutterNs = map['shutterNs'] as int; // nanoseconds
      bool isLocked = map['isLocked'] as bool;

      // If we are locked, we use the EV generated by Native Kotlin
      if (isLocked) {
         _exposureState.updateExposureFromCamera(calculatedEV);
      } else {
         // Fallback if not locked, use hardware ISO and Shutter to calc EV
         double shutterSec = hardwareShutterNs / 1000000000.0;
         double baseAperture = 1.8; // Assume generic f/1.8 for mobile
         double hardwareEV = ExposureCalculator.calculateSettingsEv(baseAperture, shutterSec, hardwareIso);
         _exposureState.updateExposureFromCamera(hardwareEV);
      }
    });
  }

  void _toggleLock() {
    final state = Provider.of<ExposureState>(context, listen: false);
    if (_isAELocked) {
      _methodChannel?.invokeMethod('unlockAE');
      setState(() => _isAELocked = false);
    } else {
      _methodChannel?.invokeMethod('lockAE', {'baseEV': state.ev});
      setState(() {
        _isAELocked = true;
        _lockedBaseEV = state.ev;
      });
    }
    HapticFeedback.mediumImpact();
  }

  @override
  Widget build(BuildContext context) {
    final state = context.watch<ExposureState>();
    final isDark = state.themeMode == ThemeMode.system
        ? MediaQuery.platformBrightnessOf(context) == Brightness.dark
        : state.themeMode == ThemeMode.dark;

    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: [
          Positioned.fill(
            child: GestureDetector(
              onTapDown: (details) {
                if (_methodChannel != null) {
                  final RenderBox box = context.findRenderObject() as RenderBox;
                  final size = box.size;
                  final dx = details.localPosition.dx / size.width;
                  final dy = details.localPosition.dy / size.height;
                  _methodChannel!.invokeMethod('setMeteringPoint', {'x': dx, 'y': dy});
                  HapticFeedback.lightImpact();
                  setState(() => _meterPoint = Offset(dx, dy));
                }
              },
              onScaleUpdate: (details) {
                if (_methodChannel != null) {
                  setState(() {
                    _currentZoom = (_currentZoom * details.scale).clamp(1.0, 5.0);
                  });
                  _methodChannel!.invokeMethod('setZoom', {'zoom': _currentZoom});
                }
              },
              child: Stack(
                children: [
                  Positioned.fill(
                    child: ClipRect(
                      child: FittedBox(
                        fit: BoxFit.contain,
                        child: SizedBox(
                          width: 480, // Portrait aspect ratio (reversed 640x480)
                          height: 640,
                          child: AndroidView(
                            viewType: 'NativeCameraView',
                            onPlatformViewCreated: _onPlatformViewCreated,
                            creationParamsCodec: const StandardMessageCodec(),
                          ),
                        ),
                      ),
                    ),
                  ),
                  if (_meterPoint != null)
                    Positioned(
                      left: _meterPoint!.dx * MediaQuery.of(context).size.width - 20,
                      top: _meterPoint!.dy * MediaQuery.of(context).size.height - 20,
                      child: Container(
                        width: 40,
                        height: 40,
                        decoration: BoxDecoration(
                          border: Border.all(color: const Color(0xFF8EFF71), width: 1.5),
                          shape: BoxShape.circle,
                        ),
                      ),
                    ),
                ],
              ),
            ),
          ),
          
          // Zoom Slider
          Positioned(
            right: 0,
            bottom: 250,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  '${(24 * _currentZoom).toInt()}mm',
                  style: const TextStyle(
                    color: Colors.white,
                    fontFamily: 'SpaceGrotesk',
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                    shadows: [Shadow(color: Colors.black87, blurRadius: 4)],
                  ),
                ),
                const SizedBox(height: 8),
                SizedBox(
                  height: 200,
                  child: RotatedBox(
                    quarterTurns: 3,
                    child: Slider(
                      value: _currentZoom,
                      min: 1.0,
                      max: 5.0,
                      activeColor: const Color(0xFF8EFF71),
                      inactiveColor: Colors.white24,
                      onChanged: (val) {
                        setState(() => _currentZoom = val);
                        if (_methodChannel != null) {
                          _methodChannel!.invokeMethod('setZoom', {'zoom': _currentZoom});
                        }
                      },
                    ),
                  ),
                ),
              ],
            ),
          ),
          
          if (_showHistogram)
            Positioned(
              top: 100,
              left: 16,
              right: 16,
              height: 100,
              child: Opacity(
                opacity: 0.6,
                child: CustomPaint(
                  painter: HistogramPainter(
                    _histogramR,
                    _histogramG,
                    _histogramB,
                    _maxHistogramValue,
                  ),
                ),
              ),
            ),
            
          SafeArea(
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      IconButton(
                        icon: const Icon(Icons.arrow_back, color: Colors.white, size: 28),
                        onPressed: () => Navigator.pop(context),
                      ),
                      if (state.selectedFilm != null)
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                          decoration: BoxDecoration(
                            color: const Color(0xFFFBBC00),
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: Text(
                            state.selectedFilm!.name,
                            style: const TextStyle(
                              color: Colors.black,
                              fontWeight: FontWeight.bold,
                              fontSize: 12,
                            ),
                          ),
                        ),
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          IconButton(
                            icon: Icon(_isAELocked ? Icons.lock : Icons.lock_open,
                                color: _isAELocked ? const Color(0xFFFBBC00) : Colors.white, size: 28),
                            onPressed: _toggleLock,
                          ),
                          IconButton(
                            icon: Icon(_showHistogram ? Icons.bar_chart : Icons.show_chart,
                                color: Colors.white, size: 28),
                            onPressed: () => setState(() => _showHistogram = !_showHistogram),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                const Spacer(),
                _buildViewfinderHUD(context, state),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildViewfinderHUD(BuildContext context, ExposureState state) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.black.withValues(alpha: 0.9),
        borderRadius: const BorderRadius.only(topLeft: Radius.circular(24), topRight: Radius.circular(24)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Row(
            children: [
              Expanded(
                child: _buildProReadoutBlock('f/', state.aperture.toStringAsFixed(1), Colors.white,
                  onMinus: state.target == CalculationTarget.aperture ? null : () {
                    int idx = ExposureCalculator.apertureValues.indexOf(state.aperture);
                    double next = ExposureCalculator.apertureValues[(idx - 1 + ExposureCalculator.apertureValues.length) % ExposureCalculator.apertureValues.length];
                    state.setAperture(next);
                  },
                  onPlus: state.target == CalculationTarget.aperture ? null : () {
                    int idx = ExposureCalculator.apertureValues.indexOf(state.aperture);
                    double next = ExposureCalculator.apertureValues[(idx + 1) % ExposureCalculator.apertureValues.length];
                    state.setAperture(next);
                  },
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _buildProReadoutBlock('iso', '${state.iso}', Colors.white,
                  onMinus: (state.target == CalculationTarget.iso || state.selectedFilm != null) ? null : () {
                    int idx = ExposureCalculator.isoValues.indexOf(state.iso);
                    int next = ExposureCalculator.isoValues[(idx - 1 + ExposureCalculator.isoValues.length) % ExposureCalculator.isoValues.length];
                    state.setIso(next);
                  },
                  onPlus: (state.target == CalculationTarget.iso || state.selectedFilm != null) ? null : () {
                    int idx = ExposureCalculator.isoValues.indexOf(state.iso);
                    int next = ExposureCalculator.isoValues[(idx + 1) % ExposureCalculator.isoValues.length];
                    state.setIso(next);
                  },
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: _buildProReadoutBlock('sec', ExposureCalculator.formatShutterSpeed(state.shutterSpeed), const Color(0xFFEE7D77),
                  onMinus: (state.target == CalculationTarget.shutter || state.fpsOption != null) ? null : () {
                    int idx = ExposureCalculator.shutterValues.indexOf(state.shutterSpeed);
                    double next = ExposureCalculator.shutterValues[(idx - 1 + ExposureCalculator.shutterValues.length) % ExposureCalculator.shutterValues.length];
                    state.setShutterSpeed(next);
                  },
                  onPlus: (state.target == CalculationTarget.shutter || state.fpsOption != null) ? null : () {
                    int idx = ExposureCalculator.shutterValues.indexOf(state.shutterSpeed);
                    double next = ExposureCalculator.shutterValues[(idx + 1) % ExposureCalculator.shutterValues.length];
                    state.setShutterSpeed(next);
                  },
                ),
              ),
              const SizedBox(width: 12),
              Expanded(child: _buildProReadoutBlock('ev', state.ev.toStringAsFixed(1), Colors.white)),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildProReadoutBlock(String label, String value, Color valueColor, {VoidCallback? onMinus, VoidCallback? onPlus}) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
      decoration: BoxDecoration(
        color: const Color(0xFF222222),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label.toUpperCase(),
            style: const TextStyle(
              color: Color(0xFF9D9E9E),
              fontSize: 10,
              fontWeight: FontWeight.bold,
              letterSpacing: 1.2,
            ),
          ),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              if (onMinus != null)
                GestureDetector(
                  onTap: onMinus,
                  child: const Icon(Icons.remove, color: Colors.white54, size: 20),
                )
              else
                const SizedBox(width: 20),
                
              Text(
                value,
                style: TextStyle(
                  color: valueColor,
                  fontFamily: 'Inter',
                  fontWeight: FontWeight.w700,
                  fontSize: 20,
                ),
              ),
              
              if (onPlus != null)
                GestureDetector(
                  onTap: onPlus,
                  child: const Icon(Icons.add, color: Colors.white54, size: 20),
                )
              else
                const SizedBox(width: 20),
            ],
          ),
        ],
      ),
    );
  }
}

class HistogramPainter extends CustomPainter {
  final List<int> r, g, b;
  final int maxVal;
  HistogramPainter(this.r, this.g, this.b, this.maxVal);

  @override
  void paint(Canvas canvas, Size size) {
    if (maxVal == 0) return;
    final paintR = Paint()..color = Colors.red.withValues(alpha: 0.6)..strokeWidth = 1;
    final paintG = Paint()..color = Colors.green.withValues(alpha: 0.6)..strokeWidth = 1;
    final paintB = Paint()..color = Colors.blue.withValues(alpha: 0.6)..strokeWidth = 1;

    final double step = size.width / 256;
    for (int i = 0; i < 256; i++) {
      final double x = i * step;
      final double yr = size.height - (r[i] / maxVal) * size.height;
      final double yg = size.height - (g[i] / maxVal) * size.height;
      final double yb = size.height - (b[i] / maxVal) * size.height;
      canvas.drawLine(Offset(x, size.height), Offset(x, yr), paintR);
      canvas.drawLine(Offset(x, size.height), Offset(x, yg), paintG);
      canvas.drawLine(Offset(x, size.height), Offset(x, yb), paintB);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
